# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tensorflow_pb2 as tensorflow__pb2


class ReccomandationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/pridict.Reccomandation/Predict',
        request_serializer=tensorflow__pb2.queryRequest.SerializeToString,
        response_deserializer=tensorflow__pb2.queryResponse.FromString,
        )
    self.SimillarItem = channel.unary_unary(
        '/pridict.Reccomandation/SimillarItem',
        request_serializer=tensorflow__pb2.simillarItemRequest.SerializeToString,
        response_deserializer=tensorflow__pb2.simillarItemResponse.FromString,
        )
    self.SimillarUser = channel.unary_unary(
        '/pridict.Reccomandation/SimillarUser',
        request_serializer=tensorflow__pb2.simillarUserRequest.SerializeToString,
        response_deserializer=tensorflow__pb2.simillarUserResponse.FromString,
        )


class ReccomandationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimillarItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimillarUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReccomandationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=tensorflow__pb2.queryRequest.FromString,
          response_serializer=tensorflow__pb2.queryResponse.SerializeToString,
      ),
      'SimillarItem': grpc.unary_unary_rpc_method_handler(
          servicer.SimillarItem,
          request_deserializer=tensorflow__pb2.simillarItemRequest.FromString,
          response_serializer=tensorflow__pb2.simillarItemResponse.SerializeToString,
      ),
      'SimillarUser': grpc.unary_unary_rpc_method_handler(
          servicer.SimillarUser,
          request_deserializer=tensorflow__pb2.simillarUserRequest.FromString,
          response_serializer=tensorflow__pb2.simillarUserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pridict.Reccomandation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
