# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow.proto',
  package='pridict',
  syntax='proto2',
  serialized_pb=_b('\n\x10tensorflow.proto\x12\x07pridict\"*\n\x0cqueryRequest\x12\x0c\n\x04user\x18\x01 \x02(\x05\x12\x0c\n\x04item\x18\x02 \x02(\x05\"\x1f\n\rqueryResponse\x12\x0e\n\x06result\x18\x01 \x02(\x03\"#\n\x13simillarUserRequest\x12\x0c\n\x04user\x18\x01 \x02(\x05\"&\n\x14simillarUserResponse\x12\x0e\n\x06result\x18\x01 \x02(\x03\"#\n\x13simillarItemRequest\x12\x0c\n\x04item\x18\x01 \x02(\x05\"&\n\x14simillarItemResponse\x12\x0e\n\x06result\x18\x01 \x02(\x03\x32\xea\x01\n\x0eReccomandation\x12:\n\x07Predict\x12\x15.pridict.queryRequest\x1a\x16.pridict.queryResponse\"\x00\x12M\n\x0cSimillarItem\x12\x1c.pridict.simillarItemRequest\x1a\x1d.pridict.simillarItemResponse\"\x00\x12M\n\x0cSimillarUser\x12\x1c.pridict.simillarUserRequest\x1a\x1d.pridict.simillarUserResponse\"\x00')
)




_QUERYREQUEST = _descriptor.Descriptor(
  name='queryRequest',
  full_name='pridict.queryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='pridict.queryRequest.user', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='pridict.queryRequest.item', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=71,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='queryResponse',
  full_name='pridict.queryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pridict.queryResponse.result', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=104,
)


_SIMILLARUSERREQUEST = _descriptor.Descriptor(
  name='simillarUserRequest',
  full_name='pridict.simillarUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='pridict.simillarUserRequest.user', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=141,
)


_SIMILLARUSERRESPONSE = _descriptor.Descriptor(
  name='simillarUserResponse',
  full_name='pridict.simillarUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pridict.simillarUserResponse.result', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=181,
)


_SIMILLARITEMREQUEST = _descriptor.Descriptor(
  name='simillarItemRequest',
  full_name='pridict.simillarItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='pridict.simillarItemRequest.item', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=218,
)


_SIMILLARITEMRESPONSE = _descriptor.Descriptor(
  name='simillarItemResponse',
  full_name='pridict.simillarItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pridict.simillarItemResponse.result', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=258,
)

DESCRIPTOR.message_types_by_name['queryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['queryResponse'] = _QUERYRESPONSE
DESCRIPTOR.message_types_by_name['simillarUserRequest'] = _SIMILLARUSERREQUEST
DESCRIPTOR.message_types_by_name['simillarUserResponse'] = _SIMILLARUSERRESPONSE
DESCRIPTOR.message_types_by_name['simillarItemRequest'] = _SIMILLARITEMREQUEST
DESCRIPTOR.message_types_by_name['simillarItemResponse'] = _SIMILLARITEMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

queryRequest = _reflection.GeneratedProtocolMessageType('queryRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUEST,
  __module__ = 'tensorflow_pb2'
  # @@protoc_insertion_point(class_scope:pridict.queryRequest)
  ))
_sym_db.RegisterMessage(queryRequest)

queryResponse = _reflection.GeneratedProtocolMessageType('queryResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESPONSE,
  __module__ = 'tensorflow_pb2'
  # @@protoc_insertion_point(class_scope:pridict.queryResponse)
  ))
_sym_db.RegisterMessage(queryResponse)

simillarUserRequest = _reflection.GeneratedProtocolMessageType('simillarUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMILLARUSERREQUEST,
  __module__ = 'tensorflow_pb2'
  # @@protoc_insertion_point(class_scope:pridict.simillarUserRequest)
  ))
_sym_db.RegisterMessage(simillarUserRequest)

simillarUserResponse = _reflection.GeneratedProtocolMessageType('simillarUserResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMILLARUSERRESPONSE,
  __module__ = 'tensorflow_pb2'
  # @@protoc_insertion_point(class_scope:pridict.simillarUserResponse)
  ))
_sym_db.RegisterMessage(simillarUserResponse)

simillarItemRequest = _reflection.GeneratedProtocolMessageType('simillarItemRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMILLARITEMREQUEST,
  __module__ = 'tensorflow_pb2'
  # @@protoc_insertion_point(class_scope:pridict.simillarItemRequest)
  ))
_sym_db.RegisterMessage(simillarItemRequest)

simillarItemResponse = _reflection.GeneratedProtocolMessageType('simillarItemResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMILLARITEMRESPONSE,
  __module__ = 'tensorflow_pb2'
  # @@protoc_insertion_point(class_scope:pridict.simillarItemResponse)
  ))
_sym_db.RegisterMessage(simillarItemResponse)



_RECCOMANDATION = _descriptor.ServiceDescriptor(
  name='Reccomandation',
  full_name='pridict.Reccomandation',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=261,
  serialized_end=495,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='pridict.Reccomandation.Predict',
    index=0,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SimillarItem',
    full_name='pridict.Reccomandation.SimillarItem',
    index=1,
    containing_service=None,
    input_type=_SIMILLARITEMREQUEST,
    output_type=_SIMILLARITEMRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SimillarUser',
    full_name='pridict.Reccomandation.SimillarUser',
    index=2,
    containing_service=None,
    input_type=_SIMILLARUSERREQUEST,
    output_type=_SIMILLARUSERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECCOMANDATION)

DESCRIPTOR.services_by_name['Reccomandation'] = _RECCOMANDATION

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ReccomandationStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Predict = channel.unary_unary(
          '/pridict.Reccomandation/Predict',
          request_serializer=queryRequest.SerializeToString,
          response_deserializer=queryResponse.FromString,
          )
      self.SimillarItem = channel.unary_unary(
          '/pridict.Reccomandation/SimillarItem',
          request_serializer=simillarItemRequest.SerializeToString,
          response_deserializer=simillarItemResponse.FromString,
          )
      self.SimillarUser = channel.unary_unary(
          '/pridict.Reccomandation/SimillarUser',
          request_serializer=simillarUserRequest.SerializeToString,
          response_deserializer=simillarUserResponse.FromString,
          )


  class ReccomandationServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Predict(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SimillarItem(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SimillarUser(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ReccomandationServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Predict': grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=queryRequest.FromString,
            response_serializer=queryResponse.SerializeToString,
        ),
        'SimillarItem': grpc.unary_unary_rpc_method_handler(
            servicer.SimillarItem,
            request_deserializer=simillarItemRequest.FromString,
            response_serializer=simillarItemResponse.SerializeToString,
        ),
        'SimillarUser': grpc.unary_unary_rpc_method_handler(
            servicer.SimillarUser,
            request_deserializer=simillarUserRequest.FromString,
            response_serializer=simillarUserResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'pridict.Reccomandation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaReccomandationServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Predict(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SimillarItem(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SimillarUser(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaReccomandationStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Predict(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Predict.future = None
    def SimillarItem(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SimillarItem.future = None
    def SimillarUser(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SimillarUser.future = None


  def beta_create_Reccomandation_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('pridict.Reccomandation', 'Predict'): queryRequest.FromString,
      ('pridict.Reccomandation', 'SimillarItem'): simillarItemRequest.FromString,
      ('pridict.Reccomandation', 'SimillarUser'): simillarUserRequest.FromString,
    }
    response_serializers = {
      ('pridict.Reccomandation', 'Predict'): queryResponse.SerializeToString,
      ('pridict.Reccomandation', 'SimillarItem'): simillarItemResponse.SerializeToString,
      ('pridict.Reccomandation', 'SimillarUser'): simillarUserResponse.SerializeToString,
    }
    method_implementations = {
      ('pridict.Reccomandation', 'Predict'): face_utilities.unary_unary_inline(servicer.Predict),
      ('pridict.Reccomandation', 'SimillarItem'): face_utilities.unary_unary_inline(servicer.SimillarItem),
      ('pridict.Reccomandation', 'SimillarUser'): face_utilities.unary_unary_inline(servicer.SimillarUser),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Reccomandation_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('pridict.Reccomandation', 'Predict'): queryRequest.SerializeToString,
      ('pridict.Reccomandation', 'SimillarItem'): simillarItemRequest.SerializeToString,
      ('pridict.Reccomandation', 'SimillarUser'): simillarUserRequest.SerializeToString,
    }
    response_deserializers = {
      ('pridict.Reccomandation', 'Predict'): queryResponse.FromString,
      ('pridict.Reccomandation', 'SimillarItem'): simillarItemResponse.FromString,
      ('pridict.Reccomandation', 'SimillarUser'): simillarUserResponse.FromString,
    }
    cardinalities = {
      'Predict': cardinality.Cardinality.UNARY_UNARY,
      'SimillarItem': cardinality.Cardinality.UNARY_UNARY,
      'SimillarUser': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'pridict.Reccomandation', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
